# Generated by Django 5.2.8 on 2025-12-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='file',
            field=models.FileField(max_length=500, upload_to='models/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='static/default_avatar.jpeg', max_length=500, upload_to='users/avatars/'),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='images/'),
        ),
    ]
