# Generated by Django 5.2.8 on 2025-12-18 07:28

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='file',
            field=models.FileField(max_length=500, upload_to=api.models.model_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['safetensors', 'ckpt', 'pt'])]),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=api.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.avatar_directory_path),
        ),
    ]
