# Generated by Django 5.2.8 on 2025-12-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
