# Generated by Django 5.2.8 on 2025-12-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_generatedimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
